### PR TITLE
[FEATURE] Sync htdocs folder between host and guest machine

### PR DESCRIPTION
**Pull request by ghost**
Sync htdocs folder on the host machine to the guest machine,
allowing you to continue working on your project's files on
your host machine, but use the resources in the guest
machine to run your project.

### CODE REVIEW

**Comment by ghost** [comment]
I don’t know if this pull request meets your plans and the way you want to use this vagrant box. maybe you also find it useful to sync the htdocs folder. looking forward to hearing your opinion about it.

**Comment by tlayh** [comment]
Hi Roland, I don't like syncing the folders. On some computers, e.g. on Windows machines, it makes so box really slow if you sync this, because the box is writing logfiles and cache files to your windows machine too. Did you recognize any performance changes?

**Comment by ghost** [comment]
hi thomas, heard about this issue. did not experience it on my own - mainly because i did not use vagrant that much until recently and i do not use windows. have you ever tried to use nfs to improve performance when using synced folder? [1]

[1] http://docs.vagrantup.com/v2/synced-folders/nfs.html

**Comment by tlayh** [comment]
I have thrown away my windows computer a year ago or so, so I will not have this problem. But I also want to have this box working for windows people.

Thx for the link, I have never tried that.

**Pull request closed without merging**
